/**
 * Pixel-art sprites for every item, 16×16, drawn with palette letters.
 * '.' is transparent. Run `npm run art` to regenerate public/objets/*.svg.
 *
 * Shared palette letters (a sprite can override or add its own):
 *   k outline   w white   x near-black
 *   d/g/G/l     dark→light gray      S/s steel / silver
 *   n/b/B/t/T   dark→pale brown / tan
 *   m/r/R       maroon / red / light red      o/O orange / light orange
 *   y/Y/L       amber / yellow / pale yellow  z gold
 *   F/f/e/E     forest→light green
 *   U/u/c/C/a   navy / blue / sky / pale sky / cyan
 *   v/p/P       violet / purple / light purple
 *   i/I         pink / light pink            h skin
 */
export const SIZE = 16

export const PALETTE = {
  k: '#1b1730',
  w: '#ffffff',
  x: '#0b0a14',
  d: '#374151',
  g: '#6b7280',
  G: '#9ca3af',
  l: '#d1d5db',
  S: '#94a3b8',
  s: '#e2e8f0',
  n: '#4a2c17',
  b: '#8b5a2b',
  B: '#b5793e',
  t: '#d9a066',
  T: '#f3d9a4',
  m: '#7f1d1d',
  r: '#dc2626',
  R: '#f87171',
  o: '#ea580c',
  O: '#fb923c',
  y: '#f59e0b',
  Y: '#fde047',
  L: '#fef9c3',
  z: '#fcd34d',
  F: '#14532d',
  f: '#15803d',
  e: '#22c55e',
  E: '#86efac',
  U: '#1e3a8a',
  u: '#2563eb',
  c: '#38bdf8',
  C: '#bae6fd',
  a: '#67e8f9',
  v: '#6d28d9',
  p: '#a855f7',
  P: '#d8b4fe',
  i: '#ec4899',
  I: '#f9a8d4',
  h: '#fcd5b5',
}

/** @type {Record<string, { rows: string[], palette?: Record<string, string> }>} */
export const SPRITES = {
  // ── Starters ────────────────────────────────────────────────────────
  'obj-01': { // Mossy Rock
    rows: [
      '................',
      '................',
      '......kkkk......',
      '....kkeeeekk....',
      '...keeEEeeGgk...',
      '..kEeGGGGGGGgk..',
      '..kGGGGlGGGGgk..',
      '.kGGGGllGGGGggk.',
      '.kGGGGGGGGGgggk.',
      '.kgGGGGGGGgggdk.',
      '.kggGGGGggggddk.',
      '..kgggggggdddk..',
      '..kdgggggddddk..',
      '...kddddddddk...',
      '....kkkkkkkk....',
      '................',
    ],
  },
  'obj-04': { // Oak Leaf
    rows: [
      '................',
      '.........kkk....',
      '.......kkEeek...',
      '......kEeEeeek..',
      '.....kEeeEeeek..',
      '....kEeeeEeeek..',
      '....kEeeeEeefk..',
      '...kEeeeeEeffk..',
      '...keeeeEeffk...',
      '...keeeEeffk....',
      '...keeEefffk....',
      '....keEeffk.....',
      '....kEeffk......',
      '.....kEfk.......',
      '.....kbk........',
      '....kbk.........',
    ],
  },
  'obj-07': { // Rusty Scissors
    rows: [
      '................',
      '..kk........kk..',
      '.kSsk......kSsk.',
      '.kSsbk....kbsSk.',
      '..kSsbk..kbsSk..',
      '...kSsbkkbsSk...',
      '....kSsbbsSk....',
      '.....kSssSk.....',
      '......kbbk......',
      '.....kbkkbk.....',
      '....krbkkbrk....',
      '...krrbk.kbrrk..',
      '...krrk...krrk..',
      '...krrk...krrk..',
      '....kk.....kk...',
      '................',
    ],
  },

  // ── Booster pool ────────────────────────────────────────────────────
  'obj-02': { // Ancient Menhir
    rows: [
      '................',
      '......kkkk......',
      '.....kGGGGk.....',
      '.....kGlGGk.....',
      '....kGGGlGGk....',
      '....kGGyGGGk....',
      '....kGGGGGGk....',
      '....kGyGGGGk....',
      '....kGGGGyGk....',
      '....kGGGGGGk....',
      '...kGGGyGGGGk...',
      '...kGGGGGGGGk...',
      '...kgGGGGGGgk...',
      '..kgggggggggk...',
      '.kfeeeeeeeeeefk.',
      '..kkkkkkkkkkkk..',
    ],
  },
  'obj-03': { // Meteorite
    rows: [
      '...O............',
      '..OYo...........',
      '.OYYoo..........',
      '.oYYooo.........',
      '..ooOooo........',
      '...ooooOo.......',
      '....ooookkkk....',
      '.....ookggggk...',
      '......kgggdggk..',
      '......kgdggggk..',
      '.....kggggdggk..',
      '.....kggdggggk..',
      '.....kgggggdgk..',
      '......kggggggk..',
      '.......kkkkkk...',
      '................',
    ],
  },
  'obj-05': { // Cursed Scroll
    rows: [
      '................',
      '................',
      '...kkkkkkkkkk...',
      '..kbTTTTTTTTbk..',
      '..kbkkkkkkkkbk..',
      '...kTTTTTTTTk...',
      '...kTpTTpTTTk...',
      '...kTTTTTTTTk...',
      '...kTTpTTTpTk...',
      '...kTTTTTTTTk...',
      '...kTpTTTpTTk...',
      '...kTTTTTTTTk...',
      '..kbkkkkkkkkbk..',
      '..kbTTTTTTTTbk..',
      '...kkkkkkkkkk...',
      '................',
    ],
  },
  'obj-06': { // Armored Paper
    rows: [
      '................',
      '..kkkkkkkkkkk...',
      '..kwwwwwwwwwwk..',
      '..kwSkkSkkSkwk..',
      '..kwwwwwwwwwwk..',
      '..kwwSSSSSSwwk..',
      '..kwwSlSSlSwwk..',
      '..kwwSSSSSSwwk..',
      '..kwwSlSSlSwwk..',
      '..kwwSSSSSSwwk..',
      '..kwwwwwwwwwwk..',
      '..kwSkkSkkSkwk..',
      '..kwwwwwwwwwwk..',
      '..kwwwwwwwwwwk..',
      '..kkkkkkkkkkkk..',
      '................',
    ],
  },
  'obj-08': { // Sharpened Katana
    rows: [
      '..............kk',
      '.............kwk',
      '............kwsk',
      '...........kwsk.',
      '..........kwsk..',
      '.........kwsk...',
      '........kwsk....',
      '.......kwsk.....',
      '......kwsk......',
      '.....kwsk.......',
      '....kysk........',
      '...kyyk.........',
      '..kmmk..........',
      '.kmmk...........',
      '.kmk............',
      '..k.............',
    ],
  },
  'obj-09': { // Crab Claw
    rows: [
      '................',
      '.....kkkk.......',
      '....kRRRRk......',
      '...kRrrrrRk.....',
      '..kRrrkkkrrk....',
      '..krrk...krrk...',
      '..krrk....kk....',
      '..krrrk.........',
      '...krrrk....kk..',
      '....krrrkkkkrrk.',
      '.....krrrrrrrrk.',
      '......krrrrrrk..',
      '.......krrrrk...',
      '........krrk....',
      '.........kk.....',
      '................',
    ],
  },
  'obj-10': { // Storm Lightning
    rows: [
      '................',
      '....kkkkkk......',
      '...kGGGGGGkk....',
      '..kGGGGGGGGGk...',
      '..kgGGGGGGGGgk..',
      '...kkkkkkkkkk...',
      '........kYYk....',
      '.......kYYk.....',
      '......kYYYYYk...',
      '.......kkkYYk...',
      '.........kYk....',
      '........kYk.....',
      '.......kYk......',
      '......kYk.......',
      '......kk........',
      '................',
    ],
  },
  'obj-11': { // Ice Shield
    rows: [
      '................',
      '..kkkkkkkkkkkk..',
      '.kCCCCCCCCCCCCk.',
      '.kCccccwwccccCk.',
      '.kCcccwccwcccCk.',
      '.kCcwwwwwwwwcCk.',
      '.kCcccwccwcccCk.',
      '.kCccccwwccccCk.',
      '.kCcccccccccuCk.',
      '..kCcccccccuCk..',
      '..kCcccccccuCk..',
      '...kCcccccuCk...',
      '....kCccccCk....',
      '.....kCccCk.....',
      '......kCCk......',
      '.......kk.......',
    ],
  },
  'obj-12': { // Chaos Die
    rows: [
      '................',
      '....kkkkkkkk....',
      '...kPPPPPPPPk...',
      '..kPppwpppwppPk.',
      '..kPpppppppppvk.',
      '..kPpppppppppvk.',
      '..kPppppwppppvk.',
      '..kPpppppppppvk.',
      '..kPpppppppppvk.',
      '..kPpwpppppwpvk.',
      '..kPpppppppppvk.',
      '..kPpppppppppvk.',
      '..kvvvvvvvvvvvk.',
      '...kkkkkkkkkkk..',
      '................',
      '................',
    ],
  },
  'obj-13': { // Hatchet
    rows: [
      '................',
      '.........kkkk...',
      '........kssssk..',
      '.......kslssssk.',
      '......kssssssSk.',
      '......kssssSSSk.',
      '.......kbSSSSk..',
      '......kBbkkkk...',
      '.....kBbk.......',
      '....kBbk........',
      '...kBbk.........',
      '..kBbk..........',
      '.kBbk...........',
      '.kbk............',
      '..k.............',
      '................',
    ],
  },
  'obj-14': { // Shield
    rows: [
      '................',
      '..kkkkkkkkkkkk..',
      '.kssssssssssssk.',
      '.kslsssssssssSk.',
      '.kslssssssssSSk.',
      '.kslsssyyssssSk.',
      '.kslssyyyysssSk.',
      '.kslsssyyssssSk.',
      '.kslsssssssssSk.',
      '..kslsssssssSk..',
      '..kslsssssssSk..',
      '...kslsssssSk...',
      '....ksssssSk....',
      '.....kssSSk.....',
      '......kSSk......',
      '.......kk.......',
    ],
  },
  'obj-15': { // Net
    rows: [
      '................',
      '.kkkkkkkkkkkkkk.',
      '.kttttttttttttk.',
      '.kt..t..t..t.tk.',
      '.kt..t..t..t.tk.',
      '.kttttttttttttk.',
      '.kt..t..t..t.tk.',
      '.kt..t..t..t.tk.',
      '.kttttttttttttk.',
      '.kt..t..t..t.tk.',
      '.kt..t..t..t.tk.',
      '.kttttttttttttk.',
      '.kt..t..t..t.tk.',
      '.kt..t..t..t.tk.',
      '.kttttttttttttk.',
      '.kkkkkkkkkkkkkk.',
    ],
  },
  'obj-16': { // Torch
    rows: [
      '................',
      '.......Y........',
      '......YYO.......',
      '.....YYYOo......',
      '.....YOOOo......',
      '....kOOoooRk....',
      '....kOoorrrk....',
      '.....koorrk.....',
      '......krrk......',
      '.....kSSSSk.....',
      '.....kbbbbk.....',
      '......kbbk......',
      '......kbbk......',
      '......kbbk......',
      '......kbbk......',
      '.......kk.......',
    ],
  },
  'obj-17': { // Hammer
    rows: [
      '................',
      '...kkkkkkkkkk...',
      '..kslsssssssSk..',
      '..kslsssssssSk..',
      '..ksssssssssSk..',
      '..kSSSSSSSSSSk..',
      '...kkkkbbkkkk...',
      '.......kbbk.....',
      '.......kBbk.....',
      '.......kBbk.....',
      '.......kBbk.....',
      '.......kBbk.....',
      '.......kBbk.....',
      '.......kbbk.....',
      '.......kbbk.....',
      '........kk......',
    ],
  },
  'obj-18': { // Rope
    rows: [
      '................',
      '.....kkkkkk.....',
      '...kkttttttkk...',
      '..kttbbbbbbttk..',
      '..ktbkkkkkkbtk..',
      '.kttbk....kbttk.',
      '.ktbk......kbtk.',
      '.ktbk......kbtk.',
      '.ktbk..kk..kbtk.',
      '.ktbk.ktbk.kbtk.',
      '.kttbkkbbkkbttk.',
      '..ktbbbttbbbtk..',
      '..kttttbbttttk..',
      '...kkttttttkk...',
      '.....kkkkkk.....',
      '................',
    ],
  },
  'obj-19': { // Magnet
    rows: [
      '................',
      '...kkkk..kkkk...',
      '..kssssk.kssssk.',
      '..kssssk.kssssk.',
      '..kkkkkk.kkkkkk.',
      '..krrrrk.krrrrk.',
      '..krRrrk.krrrrk.',
      '..krRrrk.krrrrk.',
      '..krRrrkkkrrrrk.',
      '..krRrrrrrrrrrk.',
      '..krRrrrrrrrrrk.',
      '...krrrrrrrrrk..',
      '....krrrrrrrk...',
      '.....krrrrrk....',
      '......kkkkk.....',
      '................',
    ],
  },
  'obj-20': { // Water Bucket
    rows: [
      '................',
      '......kkkk......',
      '.....kS..Sk.....',
      '....kS....Sk....',
      '...kS......Sk...',
      '..kkkkkkkkkkkk..',
      '..kSccccccccSk..',
      '..kSCcccCcccSk..',
      '..kSccccccccSk..',
      '...kSSSSSSSSk...',
      '...kssssssssk...',
      '...kSsssssssk...',
      '....kSssssSk....',
      '....kSSSSSSk....',
      '.....kkkkkk.....',
      '................',
    ],
  },
  'obj-21': { // Kitchen Knife
    rows: [
      '................',
      '................',
      '................',
      '................',
      '................',
      '......kkkkkkkkk.',
      '....kkssssssskxk',
      '..kkwsssssssskxk',
      '.kwwsssssssskSxk',
      '..kkkssssssskxxk',
      '.....kkkkkkkkkk.',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
  },
  'obj-22': { // Shovel
    rows: [
      '................',
      '......kkkk......',
      '.....kbbbbk.....',
      '......kkbkk.....',
      '.......kbk......',
      '.......kbk......',
      '.......kbk......',
      '.......kbk......',
      '.......kbk......',
      '.....kkkbkkk....',
      '....kssssssSk...',
      '....kslsssssk...',
      '....kssssssSk...',
      '.....kssssSk....',
      '......kssSk.....',
      '.......kkk......',
    ],
  },
  'obj-23': { // Umbrella
    rows: [
      '................',
      '.......kk.......',
      '.....kkrrkk.....',
      '...kkrrRrrrkk...',
      '..krrrRrrrrrrk..',
      '.krrrRrrrrrrrrk.',
      '.kmrrrrrmrrrrmk.',
      '.kkkkkkkkkkkkkk.',
      '.......kbk......',
      '.......kbk......',
      '.......kbk......',
      '.......kbk......',
      '.......kbk......',
      '.....kkkbk......',
      '.....kbbbk......',
      '......kkk.......',
    ],
  },
  'obj-24': { // Fire Extinguisher
    rows: [
      '................',
      '......kkk.......',
      '.....kxkxk......',
      '....kxk.kxk.....',
      '....kkk.kxk.....',
      '....krrk.kk.....',
      '...krRrrk.......',
      '...krRrrk.......',
      '...krRrrk.......',
      '...krRrrk.......',
      '...krwwrk.......',
      '...krRrrk.......',
      '...krRrrk.......',
      '...krrrrk.......',
      '....kkkk........',
      '................',
    ],
  },
  'obj-25': { // Brick
    palette: { q: '#b5452b', Q: '#d9634a', 1: '#7a2e1c' },
    rows: [
      '................',
      '................',
      '................',
      '...kkkkkkkkkkk..',
      '..kQQQQQQQQQQQk.',
      '..kQqqqqqqqqq1k.',
      '..kQqqqqqqqqq1k.',
      '..kQqqqqqqqqq1k.',
      '..kQqqqqqqqqq1k.',
      '..kQqqqqqqqqq1k.',
      '..k11111111111k.',
      '...kkkkkkkkkkk..',
      '................',
      '................',
      '................',
      '................',
    ],
  },
  'obj-26': { // Duct Tape
    rows: [
      '................',
      '.....kkkkkk.....',
      '...kkGGGGGGkk...',
      '..kGGGGGGGGGGk..',
      '..kGGkkkkkkGGk..',
      '.kGGk......kGGk.',
      '.kGk........kGk.',
      '.kGk........kGk.',
      '.kGk........kGk.',
      '.kGk........kGk.',
      '.kGGk......kGGk.',
      '..kGGkkkkkkGGk..',
      '..kGGGGGGGGGGk..',
      '...kkGGGGGGGkkk.',
      '.....kkkkkkGGGk.',
      '...........kkkk.',
    ],
  },
  'obj-27': { // Flashlight
    rows: [
      '................',
      '................',
      '.........kkk....',
      '.........kSSk.L.',
      '.kkkkkkkkkSSkLL.',
      '.kyyyyyyykSwkLL.',
      '.kYyyyyyykSwkLLL',
      '.kYyyyyyykSwkLLL',
      '.kyyyyyyykSwkLL.',
      '.kkkkkkkkkSSkLL.',
      '.........kSSk.L.',
      '.........kkk....',
      '................',
      '................',
      '................',
      '................',
    ],
  },
  'obj-28': { // Power Drill
    rows: [
      '................',
      '................',
      '....kkkkkkkkk...',
      '...kyyyyyyyyyk..',
      '.kkkyYyyyyyyyk..',
      '.kSSkyyyyyyyykk.',
      '.kSSkyyyyyyyyyk.',
      '.kkkkyyyykkkkk..',
      '....kyyyyk......',
      '.....kyyyk......',
      '.....kyyyk......',
      '.....kyyyk......',
      '.....kxxxk......',
      '.....kkkkk......',
      '................',
      '................',
    ],
  },
  'obj-29': { // Crossbow
    rows: [
      '................',
      '.kk..........kk.',
      '.kSk........kSk.',
      '.kSSkkkkkkkkSSk.',
      '..kSSSSSSSSSSk..',
      '...kkkGkkkGkk...',
      '......kbbk......',
      '......kBbk......',
      '......kBbk......',
      '......kBbk......',
      '.....kkBbkk.....',
      '....kbbBbbbk....',
      '....kkkBbkkk....',
      '......kbbk......',
      '......kkkk......',
      '................',
    ],
  },
  'obj-30': { // Grappling Hook
    rows: [
      '.......kbk......',
      '.......kbk......',
      '.......kbk......',
      '......kkbkk.....',
      '.....kSSSSSk....',
      '....kSSSSSSSk...',
      '...kSSkSSSkSSk..',
      '..kSSk.kSk.kSSk.',
      '..kSk..kSk..kSk.',
      '..kSk..kSk..kSk.',
      '.kSSk..kSk..kSSk',
      '.kSk...kSk...kSk',
      '.kkk...kkk...kkk',
      '................',
      '................',
      '................',
    ],
  },
  'obj-31': { // Slingshot
    rows: [
      '................',
      '..kk........kk..',
      '.kbbk......kbbk.',
      '.kbbkr....rkbbk.',
      '.kbbk.r..r.kbbk.',
      '..kbbk.rr.kbbk..',
      '..kbbk.kk.kbbk..',
      '...kbbkggkbbk...',
      '...kbbkkkkbbk...',
      '....kbbbbbbk....',
      '.....kbBbbk.....',
      '......kBbk......',
      '......kBbk......',
      '......kBbk......',
      '......kbbk......',
      '.......kk.......',
    ],
  },
  'obj-32': { // Boxing Glove
    rows: [
      '................',
      '.....kkkkk......',
      '...kkRRRRRkk....',
      '..kRRrrrrrRrk...',
      '.kRrrrrrrrrrrk..',
      '.krrrrrrrrrrrrk.',
      '.krrrrrrrrrrrrk.',
      '.krrkkrrrrrrrrk.',
      '.kmrkrrrrrrrrmk.',
      '..kmrkrrrrrrmk..',
      '...kmkkkkkkmk...',
      '....kwwwwwwk....',
      '....kwwwwwwk....',
      '....kmmmmmmk....',
      '.....kkkkkk.....',
      '................',
    ],
  },
  'obj-33': { // Circular Saw
    rows: [
      '................',
      '....k..kk..k....',
      '...kSkkSSkkSk...',
      '..kSSSSSSSSSSk..',
      '.kkSSSssssSSSkk.',
      '.kSSSsSkksSSSSk.',
      '.kSSSskxxkSSSSk.',
      'kkSSSskxxkSSSSkk',
      'kkSSSSkxxkSSSSkk',
      '.kSSSSSkkSSSSSk.',
      '.kkSSSSSSSSSSkk.',
      '..kSSSSSSSSSSk..',
      '...kSkkSSkkSk...',
      '....k..kk..k....',
      '................',
      '................',
    ],
  },
  'obj-34': { // Chainsaw
    rows: [
      '................',
      '................',
      '....kkkkk.......',
      '...kxxxxxk......',
      '...kxkkkxkkkkkkk',
      '..kkxxxxxkSSSSSk',
      '.koooooookssssSk',
      '.kOoooooooSSSSSk',
      '.koooooookkkkkkk',
      '.kooooook.......',
      '.kkkkkkkk.......',
      '..kxxxk.........',
      '..kkkkk.........',
      '................',
      '................',
      '................',
    ],
  },
  'obj-35': { // Flamethrower
    rows: [
      '................',
      '..............O.',
      '............OOYO',
      '....kkkkk..oOYYO',
      '...kdddddkoOYYYO',
      '...kdkkkdkkOOYOO',
      '..kkddddddkkoOo.',
      '.kddddddddddk.o.',
      '.kdddddddddddk..',
      '.kkkkddddkkkkk..',
      '....kdddk.......',
      '....kkdkk.......',
      '.....kdk........',
      '.....kkk........',
      '................',
      '................',
    ],
  },
  'obj-36': { // Heavy Armor
    rows: [
      '................',
      '..kkk......kkk..',
      '.kSSSkkkkkkSSSk.',
      '.kSssSSssSSssSk.',
      '.kSsSSSSSSSSsSk.',
      '..kkSSSSlSSSkk..',
      '...kSSSSlSSSSk..',
      '...kSSSllSSSSk..',
      '...kSSSllSSSSk..',
      '...kSSSSlSSSSk..',
      '...kdSSSSSSSdk..',
      '...kddSSSSSddk..',
      '....kdddddddk...',
      '.....kkkkkkk....',
      '................',
      '................',
    ],
  },
  'obj-37': { // Industrial Drill
    rows: [
      '................',
      '...kkkkkkkkkk...',
      '..kyyyyyyyyyyk..',
      '..kyYyyyyyyyyk..',
      '..kyyyyyyyyyyk..',
      '..kkkkkkkkkkkk..',
      '...kSSssssSSk...',
      '...kSsSSSSsSk...',
      '...kSSssssSSk...',
      '....kSsSSsSk....',
      '....kSSssSSk....',
      '.....kSsSSk.....',
      '.....kSSsSk.....',
      '......kSSk......',
      '.......kk.......',
      '................',
    ],
  },
  'obj-38': { // Cannon
    rows: [
      '................',
      '................',
      '................',
      '....kkkkkkkkkkk.',
      '..kkdddddddddddk',
      '.kddggdddddddddk',
      '.kdddddddddddddk',
      '..kkdddddddddddk',
      '....kkkkkbbkkkk.',
      '......kbbbbk....',
      '.....kbkkkkbk...',
      '.....kbkbbkbk...',
      '.....kbkkkkbk...',
      '......kbbbbk....',
      '.......kkkk.....',
      '................',
    ],
  },
  'obj-39': { // Tesla Generator
    rows: [
      '.....Y....Y.....',
      '......Y..Y......',
      '....kkkYYkkk....',
      '...kaaaaaaaak...',
      '..kaaCCCCCCaak..',
      '...kaaaaaaaak...',
      '....kooooook....',
      '.....kSSSSk.....',
      '....kooooook....',
      '.....kSSSSk.....',
      '....kooooook....',
      '.....kSSSSk.....',
      '...kkkkkkkkkk...',
      '..kddddddddddk..',
      '..kddddddddddk..',
      '..kkkkkkkkkkkk..',
    ],
  },
  'obj-40': { // Bottled Tornado
    rows: [
      '................',
      '......kkkk......',
      '......kbbk......',
      '......kbbk......',
      '.....kCCCCk.....',
      '....kCaCCCCk....',
      '...kCaGGGGCCk...',
      '...kCaGGGGGCk...',
      '...kCCaGGGCCk...',
      '...kCCGGGGCCk...',
      '...kCCCGGCCCk...',
      '...kCCCCGCCCk...',
      '...kCCCGGCCCk...',
      '...kCCCCCCCCk...',
      '....kCCCCCCk....',
      '.....kkkkkk.....',
    ],
  },
  'obj-41': { // Iron Ore
    rows: [
      '................',
      '................',
      '.....kkkkk......',
      '....kggggGkk....',
      '...kgsgggggGk...',
      '..kggggsgggggk..',
      '..kgsgggggsggk..',
      '.kgggggsggggggk.',
      '.kggggggggsgggk.',
      '.kgsggggggggggk.',
      '.kgggggsgggsgdk.',
      '..kgggggggggdk..',
      '..kdgggsgggddk..',
      '...kddddddddk...',
      '....kkkkkkkk....',
      '................',
    ],
  },
  'obj-42': { // Wood Log
    rows: [
      '................',
      '................',
      '................',
      '...kkkkkkkkkkk..',
      '..kBBBBBBBBBBkk.',
      '.kbbBbbbbbbbkTTk',
      '.kbbbbbBbbbkTtTk',
      '.kbbbbbbbbbkTtTk',
      '.kbBbbbbbbbbkTTk',
      '..kbbbbbbbbbbkk.',
      '...kkkkkkkkkkk..',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
  },
  'obj-43': { // Coal
    palette: { k: '#4b5563' },
    rows: [
      '................',
      '................',
      '......kkkkk.....',
      '....kkxxxxxkk...',
      '...kxxdxxxxxxk..',
      '..kxxxxxxxdxxxk.',
      '..kxdxxxxxxxxxk.',
      '.kxxxxxxdxxxxdxk',
      '.kxxxdxxxxxxxxxk',
      '.kxxxxxxxxdxxxxk',
      '..kxxdxxxxxxxxk.',
      '..kxxxxxxxdxxxk.',
      '...kxxxxxxxxxk..',
      '....kkxxxxxkk...',
      '......kkkkk.....',
      '................',
    ],
  },
  'obj-44': { // Gold Ingot
    rows: [
      '................',
      '................',
      '................',
      '................',
      '.....kkkkkkk....',
      '....kYYYYYYYk...',
      '...kYzzzzzzzyk..',
      '..kYzzzzzzzzzyk.',
      '..kzzzzzzzzzzyk.',
      '.kzzzzzzzzzzzyyk',
      '.kyyyyyyyyyyyyyk',
      '.kkkkkkkkkkkkkkk',
      '................',
      '................',
      '................',
      '................',
    ],
  },
  'obj-45': { // Raw Diamond
    rows: [
      '................',
      '................',
      '....kkkkkkkk....',
      '...kwaaaaaaCk...',
      '..kwaCCaaCaaCk..',
      '.kwaaaaaaaaaaCk.',
      '.kkkkkkkkkkkkkk.',
      '.kcaccccccccack.',
      '..kccaccccaccck.',
      '...kcccccccck...',
      '....kcaccack....',
      '.....kcccck.....',
      '......kcck......',
      '.......kk.......',
      '................',
      '................',
    ],
  },
  'obj-46': { // Ancient Oak
    rows: [
      '......kkkk......',
      '....kkFeeFkk....',
      '...kFeeEEeeFk...',
      '..kFeeEeeeeeFk..',
      '..keeeeeeeFeek..',
      '.kFeeEeeeeeeeFk.',
      '.keeeeeeeeFeeek.',
      '.kFeeFeeeeeeeFk.',
      '..kFeeeeFeeeFk..',
      '...kkFeeeeFkk...',
      '.....kkbbkk.....',
      '......knbk......',
      '......knbk......',
      '.....kknbkk.....',
      '....kbnnbbbk....',
      '.....kkkkkk.....',
    ],
  },
  'obj-47': { // Thorny Bramble
    rows: [
      '................',
      '.....t..........',
      '....kfk....t....',
      '...kffk...kfk...',
      '...kfk.t..kfk...',
      '..kffkkfk.kffk..',
      '..kfffffkkfffk..',
      '.t.kkffffffkk...',
      '....kfffffk..t..',
      '...kffkkfffk....',
      '..kffk..kfffk...',
      '.kffk.t..kffk...',
      '.kfk.....kfk....',
      '.kk......kk.....',
      '................',
      '................',
    ],
  },
  'obj-48': { // Poison Mushroom
    rows: [
      '................',
      '.....kkkkkk.....',
      '...kkppppppkk...',
      '..kppEppppEppk..',
      '.kppppppppppppk.',
      '.kpEpppEpppppEk.',
      '.kppppppppEpppk.',
      '.kkkkkkkkkkkkkk.',
      '....kTTTTTTk....',
      '.....kTTTTk.....',
      '.....kTtTTk.....',
      '.....kTTTTk.....',
      '.....kTtTTk.....',
      '....kTTTTTTk....',
      '....kkkkkkkk....',
      '................',
    ],
  },
  'obj-49': { // Desert Cactus
    rows: [
      '................',
      '.......kk.......',
      '......keek......',
      '..kk..keek..kk..',
      '.keek.kEek.keek.',
      '.keek.kEek.keek.',
      '.keekkkEekkkeek.',
      '.keeeeeEeeeeeek.',
      '..kkkeeEeekkkk..',
      '.....keEek......',
      '.....keEek......',
      '.....keEek......',
      '.....keeek......',
      '...kkkkkkkkkk...',
      '..kTTTTTTTTTTk..',
      '...kkkkkkkkkk...',
    ],
  },
  'obj-50': { // Climbing Vine
    rows: [
      '.......kk.......',
      '......keek......',
      '......kek.......',
      '.....kek........',
      '....kekk........',
      '...kEekek.......',
      '..kEEekek.......',
      '...kkkkek.......',
      '......kek.......',
      '......kekkk.....',
      '......kekeEk....',
      '......kekeEEk...',
      '.....kek.kkkk...',
      '.....kek........',
      '....kek.........',
      '....kk..........',
    ],
  },
  'obj-51': { // Asteroid
    rows: [
      '................',
      '.....kkkkk......',
      '...kkGGGGGkk....',
      '..kGGGgGGGGGk...',
      '..kGgddgGGgGGk..',
      '.kGGgddgGGGGGGk.',
      '.kGGGggGGGgddGk.',
      '.kGGGGGGGGgddGk.',
      '.kGgGGGGGGGggGk.',
      '.kGGGGgddgGGGGk.',
      '..kGGGgddgGGGk..',
      '..kGGGGggGGGGk..',
      '...kGGGGGGGGk...',
      '....kkGGGGkk....',
      '......kkkk......',
      '................',
    ],
  },
  'obj-52': { // Icy Comet
    rows: [
      'C...............',
      'wC..............',
      'CwC.............',
      '.CwCC...........',
      '..CwwCC.........',
      '...CCwwCC.......',
      '....CCCwwkkkk...',
      '......CCkCCCCk..',
      '.......kCwwCCCk.',
      '.......kCwCCCCk.',
      '......kCCCCCCCck',
      '......kCCCCCCcck',
      '......kcCCCCcck.',
      '.......kcccccck.',
      '........kkkkkk..',
      '................',
    ],
  },
  'obj-53': { // Moon
    rows: [
      '................',
      '.....kkkkkk.....',
      '...kkLLLLLLkk...',
      '..kLLLLGLLLLLk..',
      '..kLLGGLLLLLLk..',
      '.kLLLGGLLLLGLLk.',
      '.kLLLLLLLLGGGLk.',
      '.kLLLLLLLLLGLLk.',
      '.kLLGLLLLLLLLLk.',
      '.kLLLLLLGLLLLLk.',
      '.kLLLLLGGGLLLLk.',
      '..kLLLLLGLLLLk..',
      '..kLLLLLLLLGLk..',
      '...kkLLLLLLkk...',
      '.....kkkkkk.....',
      '................',
    ],
  },
  'obj-54': { // Sun
    rows: [
      '.......y........',
      '...y...y...y....',
      '....y.....y.....',
      '.....kkkkkk.....',
      '....kYYYYYYk....',
      '...kYYLLLYYYk...',
      'y..kYLLLLYYYk..y',
      'yykYYLLLLYYYYkyy',
      'y..kYYLLLYYYYk.y',
      '...kYYYYYYYOk...',
      '....kYYYOOOk....',
      '.....kkkkkk.....',
      '....y.....y.....',
      '...y...y...y....',
      '.......y........',
      '................',
    ],
  },
  'obj-55': { // Shooting Star
    rows: [
      '................',
      '...........kk...',
      '..........kYYk..',
      '......kkkkkYYkkk',
      '......kYYYYYYYYk',
      '.......kYYYYYYk.',
      '........kYYYYk..',
      '........kYYYYk..',
      '.......kYYkkYYk.',
      '......kYk..kYk..',
      '.....LLkk...kk..',
      '....LL..........',
      '...LL...........',
      '..LL............',
      '.L..............',
      '................',
    ],
  },
  'obj-56': { // Miniature Black Hole
    rows: [
      '................',
      '................',
      '......kkkk......',
      '....kkxxxxkk....',
      '...kxxxxxxxxk...',
      '..kxxxxxxxxxxk..',
      '.kkkkkkkkkkkkkk.',
      'kpOOppppppppOOpk',
      'kOYOOOOOOOOOOYOk',
      'kpOOppppppppOOpk',
      '.kkkkkkkkkkkkkk.',
      '..kxxxxxxxxxxk..',
      '...kxxxxxxxxk...',
      '....kkxxxxkk....',
      '......kkkk......',
      '................',
    ],
  },
  'obj-57': { // Nebula
    rows: [
      'w...............',
      '......kkk....w..',
      '....kkkpvkk.....',
      '...kpvvvppvk.k..',
      '..kpviivpvvpkpk.',
      '.kpiiivpppvvvvpk',
      '.kviipvPPpvvpvpk',
      '.kvvvvpPPPpvvvvk',
      '.kvpvvvpPpvviivk',
      '..kvvvpvvviiivk.',
      '...kvvvvvvviivk.',
      '....kkvvvvkkkk..',
      '..w...kkkk......',
      '................',
      '.............w..',
      '................',
    ],
  },
  'obj-58': { // Tralalero Tralala
    rows: [
      '................',
      '.......kk.......',
      '......kcck....k.',
      '......kccck..kck',
      '..kkkkkccckkkcck',
      '.kccccccccccccck',
      'kckxkcccccccccck',
      'kcccccccccccccck',
      'kcwwwwwwwwwwcck.',
      '.kkwkwkwkwwkkk..',
      '..kkkkkkkkkkk...',
      '.kuk..kuk..kuk..',
      'kuuukkuuukkuuuk.',
      'kwwwkkwwwkkwwwk.',
      '.kkk..kkk..kkk..',
      '................',
    ],
  },
  'obj-59': { // Bombardiro Crocodilo
    rows: [
      '................',
      '......kkkk......',
      '.....kSSSSk.....',
      '..kkkkSSSSkkkk..',
      '.kffffffffffffk.',
      'kfefkefeeeeeeefk',
      'kfeeeeeeeeeeeefk',
      'kfwkwkweeeeeeefk',
      '.kkkkkkkeeeeefk.',
      '.......keeeeek..',
      '.......kkkkkk...',
      '.........kxxk...',
      '........kxxxxk..',
      '........kxxxxk..',
      '.........kkkk...',
      '................',
    ],
  },
  'obj-60': { // Tung Tung Tung Sahur
    rows: [
      '................',
      '.....kkkkkk.....',
      '....kBBBBBBk....',
      '....kbbbbbbk.kk.',
      '....kbkbbkbk.kbk',
      '....kbbbbbbkkbk.',
      '....kbbkkbbkbk..',
      '....kbbbbbbbk...',
      '....kbbbbbbk....',
      '....kbbbbbbk....',
      '....kbbbbbbk....',
      '....kbbbbbbk....',
      '....kbbbbbbk....',
      '....knnnnnnk....',
      '....kkkkkkkk....',
      '................',
    ],
  },
  'obj-61': { // Chimpanzini Bananini
    rows: [
      '................',
      '......kk........',
      '.....kYYk.......',
      '....kYYYYk......',
      '...kYYbbbYYk....',
      '..kYYbhhhbYYk...',
      '..kYbhkhkhbYk...',
      '..kYbhhhhhbYk...',
      '..kYbhkkkhbYk...',
      '..kYYbhhhbYYk...',
      '...kYYbbbYYk....',
      '...kYYYYYYYk....',
      '....kYYYYYk.....',
      '.....kYYYk......',
      '......kYk.......',
      '.......k........',
    ],
  },
  'obj-62': { // Ballerina Cappuccina
    rows: [
      '................',
      '.....kkkkkk.....',
      '....kwwwwwwkk...',
      '....kwbbbbwkwk..',
      '....kwbbbbwkwk..',
      '....kwwwwwwkk...',
      '.....kwwwwk.....',
      '......kkkk......',
      '.....kIIIIk.....',
      '....kIiiiiIk....',
      '...kIiiiiiiIk...',
      '..kIIiiiiiiIIk..',
      '..kkkkkkkkkkkk..',
      '.....khk.khk....',
      '.....khk.khk....',
      '.....kkk.kkk....',
    ],
  },
  'obj-63': { // Lirili Larila
    rows: [
      '................',
      '....kkkkkkkk....',
      '..kkGGGGGGGGkk..',
      '.kGGGGkGGkGGGGk.',
      '.kGGGGGGGGGGGGk.',
      '.kGGkGGGGGGkGGk.',
      '..kkkGGGGGGkkk..',
      '.....kGGGGk.....',
      '......kGGk.k....',
      '......kGGk.k....',
      '.....kkGkkkk....',
      '....kfefeeek....',
      '...kfeeefeeek...',
      '...kfeeeeeeek...',
      '...kfefeeefek...',
      '....kkkkkkkk....',
    ],
  },
  'obj-64': { // Cappuccino Assassino
    rows: [
      '................',
      '.....kkkkkk.....',
      '....kTTTTTTk....',
      '....kwwwwwwkk...',
      '....kxxxxxxkwk..',
      '....kxwxxwxkwk..',
      '....kxxxxxxkk...',
      '....kwwwwwwk..k.',
      '....kwwwwwwk.ks.',
      '....kwwwwwwkksk.',
      '.....kwwwwkwsk..',
      '......kkkkkkk...',
      '........kk......',
      '.......kwwk.....',
      '.......kkkk.....',
      '................',
    ],
  },
  'obj-65': { // Boneca Ambalabu
    rows: [
      '................',
      '...kkk....kkk...',
      '..kwwwk..kwwwk..',
      '..kwxwkkkkwxwk..',
      '..kwwweeeewwwk..',
      '...kkeeeeeekk...',
      '..keeeeeeeeeek..',
      '..keekkkkkkeek..',
      '..keeeeeeeeeek..',
      '...kkkkkkkkkk...',
      '..kddddddddddk..',
      '.kddkkkkkkkkddk.',
      '.kdkgggggggkddk.',
      '.kddkkkkkkkkddk.',
      '..kddddddddddk..',
      '...kkkkkkkkkk...',
    ],
  },
}
