-- PFC · items catalog seed, GENERATED from pfc/src/mocks by scripts/gen-items-sql.mjs.
-- Re-run the script after the items team changes the catalog; the insert is idempotent.

insert into public.items (id, name, category, attack, defense, image_url, rarity, description, explicit_wins) values
  ('obj-01', 'Mossy Rock', 'ressources', 4, 7, '/objets/obj-01.svg', 'common', 'A good old stone. Solid, if not exactly fast.', null),
  ('obj-04', 'Oak Leaf', 'plantes', 3, 5, '/objets/obj-04.svg', 'common', 'Light and unassuming. Wraps around things without trying.', null),
  ('obj-07', 'Rusty Scissors', 'fight', 5, 3, '/objets/obj-07.svg', 'common', 'Still cuts. Mostly.', null),
  ('obj-02', 'Ancient Menhir', 'ressources', 7, 9, '/objets/obj-02.svg', 'rare', 'Standing for millennia. It doesn''t move, but it blocks everything.', null),
  ('obj-03', 'Meteorite', 'espace', 10, 5, '/objets/obj-03.svg', 'epic', 'Fell from the sky. Hits hard, cracks fast.', null),
  ('obj-05', 'Cursed Scroll', 'fight', 8, 4, '/objets/obj-05.svg', 'rare', 'Its runes burn anyone who reads them aloud.', null),
  ('obj-06', 'Armored Paper', 'fight', 5, 8, '/objets/obj-06.svg', 'rare', 'Folded a hundred times. No scissors have gotten through yet.', null),
  ('obj-08', 'Sharpened Katana', 'fight', 11, 4, '/objets/obj-08.svg', 'epic', 'Cuts paper before it even hits the floor.', null),
  ('obj-10', 'Storm Lightning', 'fight', 12, 2, '/objets/obj-10.svg', 'legendary', 'Ignores the usual rules. Nobody really knows what it beats.', null),
  ('obj-11', 'Ice Shield', 'fight', 2, 12, '/objets/obj-11.svg', 'epic', 'Freezes whatever it touches. Melts in the first bit of sun.', null),
  ('obj-12', 'Chaos Die', 'fight', 7, 7, '/objets/obj-12.svg', 'legendary', 'Its stats change with every roll. In theory, anyway.', null),
  ('obj-13', 'Hatchet', 'fight', 9, 4, '/objets/obj-13.svg', 'rare', 'Always ends up splitting whatever''s supposed to stop it.', array['obj-14', 'obj-11']::text[]),
  ('obj-14', 'Shield', 'fight', 3, 10, '/objets/obj-14.svg', 'common', 'Deflects hits — except from the hatchet, which gets through eventually.', array['obj-16']::text[]),
  ('obj-15', 'Net', 'fight', 4, 6, '/objets/obj-15.svg', 'uncommon', 'Wraps and traps, but doesn''t do well near open flame.', null),
  ('obj-16', 'Torch', 'fight', 8, 3, '/objets/obj-16.svg', 'rare', 'Burns anything woven or braided.', array['obj-15', 'obj-18']::text[]),
  ('obj-17', 'Hammer', 'fight', 9, 5, '/objets/obj-17.svg', 'common', 'Flattens anything that can be knocked over.', array['obj-20']::text[]),
  ('obj-18', 'Rope', 'fight', 3, 5, '/objets/obj-18.svg', 'uncommon', 'Ties down anything drawn to metal.', array['obj-19']::text[]),
  ('obj-19', 'Magnet', 'fight', 6, 6, '/objets/obj-19.svg', 'epic', 'Attracts and locks down anything containing metal.', array['obj-13', 'obj-14', 'obj-17']::text[]),
  ('obj-20', 'Water Bucket', 'fight', 4, 4, '/objets/obj-20.svg', 'uncommon', 'Puts out anything on fire.', array['obj-16']::text[]),
  ('obj-21', 'Kitchen Knife', 'fight', 6, 3, '/objets/obj-21.svg', 'common', 'Cuts clean, but rusts fast if you don''t wipe it down.', null),
  ('obj-22', 'Shovel', 'fight', 5, 7, '/objets/obj-22.svg', 'common', 'Digs, bashes, turns over soil. Simple and unbreakable.', null),
  ('obj-23', 'Umbrella', 'fight', 3, 6, '/objets/obj-23.svg', 'uncommon', 'Folds shut on the enemy like a closing leaf.', null),
  ('obj-24', 'Fire Extinguisher', 'fight', 5, 5, '/objets/obj-24.svg', 'common', 'Smothers flames in a cold blast of CO2.', null),
  ('obj-25', 'Brick', 'ressources', 6, 6, '/objets/obj-25.svg', 'common', 'Just a paving stone. Unbreakable and unimaginative.', null),
  ('obj-26', 'Duct Tape', 'fight', 2, 5, '/objets/obj-26.svg', 'uncommon', 'Fixes, sticks, immobilizes. The universal answer.', null),
  ('obj-29', 'Crossbow', 'fight', 10, 3, '/objets/obj-29.svg', 'rare', 'One well-placed bolt goes through light armor.', null),
  ('obj-30', 'Grappling Hook', 'fight', 5, 8, '/objets/obj-30.svg', 'rare', 'Latches onto anything, drags the fight where it wants.', null),
  ('obj-31', 'Slingshot', 'fight', 7, 5, '/objets/obj-31.svg', 'rare', 'Launches stones with frightening accuracy.', null),
  ('obj-32', 'Boxing Glove', 'fight', 8, 6, '/objets/obj-32.svg', 'rare', 'One hook is enough to knock anyone off balance.', null),
  ('obj-34', 'Chainsaw', 'fight', 13, 5, '/objets/obj-34.svg', 'epic', 'Doesn''t cut, it devours. Loud, vicious, feared.', null),
  ('obj-35', 'Flamethrower', 'fight', 14, 4, '/objets/obj-35.svg', 'epic', 'Turns anything woven, roped, or leafy into ash in a second.', null),
  ('obj-36', 'Heavy Armor', 'fight', 4, 15, '/objets/obj-36.svg', 'epic', 'Takes almost everything. Heavy, slow, nearly indestructible.', null),
  ('obj-37', 'Industrial Drill', 'fight', 15, 6, '/objets/obj-37.svg', 'epic', 'Bores through rock like butter. Nothing holds it back for long.', null),
  ('obj-38', 'Cannon', 'fight', 18, 3, '/objets/obj-38.svg', 'legendary', 'One blast, and there''s not much left standing.', null),
  ('obj-39', 'Tesla Generator', 'fight', 16, 8, '/objets/obj-39.svg', 'legendary', 'A continuous arc that fries any circuit nearby.', null),
  ('obj-40', 'Bottled Tornado', 'fight', 12, 12, '/objets/obj-40.svg', 'legendary', 'Captured wind that breaks loose the moment you open the cap.', null),
  ('obj-41', 'Iron Ore', 'ressources', 5, 6, '/objets/obj-41.svg', 'common', 'Straight from the mine. Rough, heavy, useful.', null),
  ('obj-42', 'Wood Log', 'ressources', 3, 5, '/objets/obj-42.svg', 'common', 'Freshly cut. Burns well, builds better.', null),
  ('obj-43', 'Coal', 'ressources', 4, 4, '/objets/obj-43.svg', 'common', 'Black, dusty, and surprisingly dense.', null),
  ('obj-44', 'Gold Ingot', 'ressources', 6, 8, '/objets/obj-44.svg', 'rare', 'Heavy in the hand, heavier in value.', null),
  ('obj-45', 'Raw Diamond', 'ressources', 9, 10, '/objets/obj-45.svg', 'epic', 'Uncut and unpolished, but already nearly impossible to scratch.', null),
  ('obj-46', 'Ancient Oak', 'plantes', 7, 13, '/objets/obj-46.svg', 'epic', 'Deep roots, decades of growth. It doesn''t budge.', null),
  ('obj-47', 'Thorny Bramble', 'plantes', 7, 3, '/objets/obj-47.svg', 'uncommon', 'Thorns that cut anyone careless enough to grab it.', null),
  ('obj-48', 'Poison Mushroom', 'plantes', 8, 3, '/objets/obj-48.svg', 'rare', 'Beautiful, tempting, and absolutely not for eating.', null),
  ('obj-49', 'Desert Cactus', 'plantes', 5, 7, '/objets/obj-49.svg', 'uncommon', 'Stores water for months. Handle with care.', null),
  ('obj-50', 'Climbing Vine', 'plantes', 4, 6, '/objets/obj-50.svg', 'uncommon', 'Grows through anything given enough time.', null),
  ('obj-51', 'Asteroid', 'espace', 9, 6, '/objets/obj-51.svg', 'rare', 'A wandering rock with nowhere in particular to be.', null),
  ('obj-52', 'Icy Comet', 'espace', 7, 7, '/objets/obj-52.svg', 'rare', 'Streaks by once, leaves a trail of frost.', null),
  ('obj-53', 'Moon', 'espace', 6, 14, '/objets/obj-53.svg', 'epic', 'Pulls the tides without lifting a finger.', null),
  ('obj-54', 'Sun', 'espace', 20, 6, '/objets/obj-54.svg', 'secret_rare', 'The center of everything. Everyone orbits it eventually.', null),
  ('obj-55', 'Shooting Star', 'espace', 10, 4, '/objets/obj-55.svg', 'rare', 'Gone in a second, but everyone makes a wish.', null),
  ('obj-56', 'Miniature Black Hole', 'espace', 22, 2, '/objets/obj-56.svg', 'secret_rare', 'Small enough to hold. Terrifying to get close to.', null),
  ('obj-57', 'Nebula', 'espace', 11, 11, '/objets/obj-57.svg', 'epic', 'A cloud of dust and light, slowly becoming something else.', null),
  ('obj-66', 'Ant', 'animaux', 3, 5, '/objets/obj-66.svg', 'common', 'Can carry fifty times its own weight. Rarely alone.', null),
  ('obj-67', 'Mouse', 'animaux', 3, 4, '/objets/obj-67.svg', 'common', 'Small, fast, and everywhere.', null),
  ('obj-68', 'Rabbit', 'animaux', 3, 5, '/objets/obj-68.svg', 'common', 'All legs, no bite.', null),
  ('obj-69', 'Sparrow', 'animaux', 4, 3, '/objets/obj-69.svg', 'common', 'Common as they come, gone before you notice.', null),
  ('obj-70', 'Squirrel', 'animaux', 4, 4, '/objets/obj-70.svg', 'common', 'Hoards food it half the time forgets where it buried.', null),
  ('obj-71', 'Frog', 'animaux', 4, 4, '/objets/obj-71.svg', 'common', 'Damp, quick, and easily startled.', null),
  ('obj-72', 'Fox', 'animaux', 6, 5, '/objets/obj-72.svg', 'uncommon', 'Clever enough to outsmart most things twice its size.', null),
  ('obj-73', 'Raccoon', 'animaux', 6, 5, '/objets/obj-73.svg', 'uncommon', 'Nimble-fingered and fearless around trash cans.', null),
  ('obj-74', 'Owl', 'animaux', 6, 4, '/objets/obj-74.svg', 'uncommon', 'Silent wings, sharper eyes.', null),
  ('obj-75', 'Wild Boar', 'animaux', 6, 7, '/objets/obj-75.svg', 'uncommon', 'Charges first, thinks never.', null),
  ('obj-76', 'Elephant', 'animaux', 7, 12, '/objets/obj-76.svg', 'uncommon', 'Too big to hunt, too smart to provoke.', null),
  ('obj-77', 'Giraffe', 'animaux', 5, 9, '/objets/obj-77.svg', 'uncommon', 'Towers over the savanna, kicks like a truck.', null),
  ('obj-78', 'Deer', 'animaux', 5, 6, '/objets/obj-78.svg', 'uncommon', 'Built to run, not to fight.', null),
  ('obj-79', 'Bat', 'animaux', 5, 4, '/objets/obj-79.svg', 'uncommon', 'Navigates by sound in total darkness.', null),
  ('obj-80', 'Wolf', 'animaux', 9, 6, '/objets/obj-80.svg', 'rare', 'Hunts in packs. Rarely loses.', null),
  ('obj-81', 'Hyena', 'animaux', 8, 6, '/objets/obj-81.svg', 'rare', 'Laughs last because it waits for the kill to finish.', null),
  ('obj-82', 'Leopard', 'animaux', 9, 6, '/objets/obj-82.svg', 'rare', 'Drags prey twice its weight up a tree.', null),
  ('obj-83', 'Crocodile', 'animaux', 9, 9, '/objets/obj-83.svg', 'rare', 'Waits for months. Strikes in a second.', null),
  ('obj-84', 'Eagle', 'animaux', 9, 5, '/objets/obj-84.svg', 'rare', 'Spots prey from impossible heights.', null),
  ('obj-85', 'Cheetah', 'animaux', 10, 4, '/objets/obj-85.svg', 'rare', 'The fastest thing on four legs, for about ten seconds.', null),
  ('obj-86', 'Komodo Dragon', 'animaux', 8, 7, '/objets/obj-86.svg', 'rare', 'A bite today, a kill in a few days.', null),
  ('obj-87', 'Anaconda', 'animaux', 8, 8, '/objets/obj-87.svg', 'rare', 'Doesn’t bite. Just doesn’t let go.', null),
  ('obj-88', 'Lion', 'animaux', 12, 8, '/objets/obj-88.svg', 'epic', 'King of the savanna, and it knows it.', null),
  ('obj-89', 'Tiger', 'animaux', 13, 7, '/objets/obj-89.svg', 'epic', 'The largest cat alive, and the quietest.', null),
  ('obj-90', 'Grizzly Bear', 'animaux', 11, 10, '/objets/obj-90.svg', 'epic', 'One swipe ends most arguments.', null),
  ('obj-91', 'Great White Shark', 'animaux', 13, 7, '/objets/obj-91.svg', 'epic', 'Apex predator of every ocean it visits.', null),
  ('obj-92', 'Orca', 'animaux', 12, 9, '/objets/obj-92.svg', 'epic', 'Hunts great whites for sport, not just food.', null),
  ('obj-93', 'Polar Bear', 'animaux', 11, 11, '/objets/obj-93.svg', 'epic', 'The largest land predator on Earth.', null),
  ('obj-94', 'Jaguar', 'animaux', 12, 8, '/objets/obj-94.svg', 'epic', 'Bites clean through turtle shells and skulls.', null),
  ('obj-95', 'Saltwater Crocodile', 'animaux', 15, 10, '/objets/obj-95.svg', 'legendary', 'The largest living reptile. Nothing in the water argues with it.', null),
  ('obj-96', 'Sperm Whale', 'animaux', 14, 12, '/objets/obj-96.svg', 'legendary', 'Dives a mile deep to hunt giant squid.', null),
  ('obj-97', 'Tyrannosaurus Rex', 'animaux', 18, 9, '/objets/obj-97.svg', 'legendary', 'Ruled the food chain for millions of years. Still does, in spirit.', null),
  ('obj-98', 'Megalodon', 'animaux', 20, 8, '/objets/obj-98.svg', 'secret_rare', 'The largest predatory shark to ever exist. Nothing hunted it back.', null),
  ('obj-99', 'Kraken', 'animaux', 17, 13, '/objets/obj-99.svg', 'secret_rare', 'Sailors blamed it for centuries. Sailors were right.', null),
  ('obj-100', 'Wooden Cart', 'vehicules', 3, 5, '/objets/obj-100.svg', 'common', 'Pulled, pushed, or dragged. Gets there eventually.', null),
  ('obj-101', 'Bicycle', 'vehicules', 3, 4, '/objets/obj-101.svg', 'common', 'Two wheels, zero emissions, endless knee pain.', null),
  ('obj-102', 'Rowboat', 'vehicules', 3, 5, '/objets/obj-102.svg', 'common', 'Goes exactly as fast as you row it.', null),
  ('obj-103', 'Skateboard', 'vehicules', 4, 3, '/objets/obj-103.svg', 'common', 'Four wheels and a prayer.', null),
  ('obj-104', 'Steam Locomotive', 'vehicules', 8, 6, '/objets/obj-104.svg', 'uncommon', 'The invention that put horses out of a job.', null),
  ('obj-105', 'Hot Air Balloon', 'vehicules', 4, 6, '/objets/obj-105.svg', 'uncommon', 'Goes wherever the wind decides.', null),
  ('obj-106', 'Motorcycle', 'vehicules', 7, 4, '/objets/obj-106.svg', 'uncommon', 'All the speed, none of the doors.', null),
  ('obj-107', 'Sailing Ship', 'vehicules', 6, 8, '/objets/obj-107.svg', 'uncommon', 'Crossed oceans centuries before engines existed.', null),
  ('obj-108', 'Zeppelin', 'vehicules', 5, 7, '/objets/obj-108.svg', 'uncommon', 'Elegant, silent, and famously flammable.', null),
  ('obj-109', 'Snowmobile', 'vehicules', 7, 5, '/objets/obj-109.svg', 'uncommon', 'A motorcycle that gave up on wheels entirely.', null),
  ('obj-110', 'Automobile', 'vehicules', 8, 7, '/objets/obj-110.svg', 'rare', 'Changed how the whole world gets around.', null),
  ('obj-111', 'Pickup Truck', 'vehicules', 9, 8, '/objets/obj-111.svg', 'rare', 'Hauls almost anything, complains rarely.', null),
  ('obj-112', 'Cargo Ship', 'vehicules', 8, 10, '/objets/obj-112.svg', 'rare', 'Moves more freight in a week than a truck does in a year.', null),
  ('obj-113', 'Propeller Airplane', 'vehicules', 10, 6, '/objets/obj-113.svg', 'rare', 'The first machine to truly conquer the sky.', null),
  ('obj-114', 'Tank', 'vehicules', 11, 12, '/objets/obj-114.svg', 'rare', 'Treads over anything in a straight line.', null),
  ('obj-115', 'Container Ship', 'vehicules', 9, 11, '/objets/obj-115.svg', 'rare', 'Carries a small city’s worth of goods in one trip.', null),
  ('obj-116', 'Fighter Jet', 'vehicules', 15, 6, '/objets/obj-116.svg', 'epic', 'Breaks the sound barrier before breakfast.', null),
  ('obj-117', 'Attack Helicopter', 'vehicules', 14, 8, '/objets/obj-117.svg', 'epic', 'Hovers exactly where it wants to be.', null),
  ('obj-118', 'Submarine', 'vehicules', 12, 12, '/objets/obj-118.svg', 'epic', 'Disappears beneath the waves for months at a time.', null),
  ('obj-119', 'Bullet Train', 'vehicules', 11, 10, '/objets/obj-119.svg', 'epic', 'Faster than most planes taxi to the runway.', null),
  ('obj-120', 'Space Shuttle', 'vehicules', 13, 9, '/objets/obj-120.svg', 'epic', 'Left the atmosphere and came back to fly again.', null),
  ('obj-121', 'Hypercar', 'vehicules', 15, 5, '/objets/obj-121.svg', 'epic', 'Handmade, absurd, and gone in a blink.', null),
  ('obj-122', 'Stealth Bomber', 'vehicules', 18, 6, '/objets/obj-122.svg', 'legendary', 'Flies past radar like it was never there.', null),
  ('obj-123', 'Aircraft Carrier', 'vehicules', 14, 16, '/objets/obj-123.svg', 'legendary', 'A floating airbase the size of a small town.', null),
  ('obj-124', 'Formula 1 Car', 'vehicules', 17, 5, '/objets/obj-124.svg', 'legendary', 'Built for one purpose: being first.', null),
  ('obj-125', 'Mars Rover', 'vehicules', 10, 14, '/objets/obj-125.svg', 'secret_rare', 'Outlived its own mission by over a decade, alone on another planet.', null),
  ('obj-126', 'Reusable Orbital Rocket', 'vehicules', 19, 8, '/objets/obj-126.svg', 'secret_rare', 'Leaves the planet, then lands itself to do it again.', null),
  ('obj-129', 'Spear', 'fight', 6, 4, '/objets/obj-129.svg', 'common', 'Keeps things at a distance, permanently.', null),
  ('obj-131', 'Longbow', 'fight', 8, 4, '/objets/obj-131.svg', 'uncommon', 'Won wars long before gunpowder existed.', null),
  ('obj-132', 'Mace', 'fight', 8, 5, '/objets/obj-132.svg', 'uncommon', 'Armor doesn’t care about edges. It cares about this.', null),
  ('obj-135', 'Flintlock Pistol', 'fight', 9, 3, '/objets/obj-135.svg', 'rare', 'One shot, then a long reload. Made it count.', null),
  ('obj-139', 'Pistol', 'fight', 12, 4, '/objets/obj-139.svg', 'epic', 'Compact, reliable, and everywhere.', null),
  ('obj-141', 'Sniper Rifle', 'fight', 14, 3, '/objets/obj-141.svg', 'epic', 'One shot, one very long walk to get there.', null),
  ('obj-142', 'Grenade', 'fight', 14, 2, '/objets/obj-142.svg', 'epic', 'Pull the pin, then really commit to leaving.', null),
  ('obj-143', 'AK-47', 'fight', 16, 5, '/objets/obj-143.svg', 'legendary', 'The most produced rifle in history. Reliable in any conditions.', null),
  ('obj-146', 'Railgun', 'fight', 21, 3, '/objets/obj-146.svg', 'secret_rare', 'No gunpowder. Just enough electromagnetism to outrun sound.', null),
  ('obj-148', 'Space Dust', 'espace', 3, 4, '/objets/obj-148.svg', 'common', 'The raw material every planet started as.', null),
  ('obj-149', 'Ice Chunk', 'espace', 4, 5, '/objets/obj-149.svg', 'common', 'Frozen leftovers drifting since the solar system formed.', null),
  ('obj-150', 'Small Moon', 'espace', 5, 8, '/objets/obj-150.svg', 'uncommon', 'Too small to matter, until it’s the only thing in the sky.', null),
  ('obj-151', 'Meteor Shower', 'espace', 7, 3, '/objets/obj-151.svg', 'uncommon', 'Dozens of wishes burning up at once.', null),
  ('obj-152', 'Asteroid Belt', 'espace', 6, 7, '/objets/obj-152.svg', 'uncommon', 'A whole ring of rocks that never became a planet.', null),
  ('obj-153', 'Dwarf Planet', 'espace', 7, 9, '/objets/obj-153.svg', 'rare', 'Big enough to be round, not big enough to clear its orbit.', null),
  ('obj-154', 'Satellite', 'espace', 6, 6, '/objets/obj-154.svg', 'rare', 'Watches everything, says nothing.', null),
  ('obj-155', 'White Dwarf', 'espace', 10, 6, '/objets/obj-155.svg', 'rare', 'A dead star, still hotter than anything on Earth.', null),
  ('obj-156', 'Gas Giant', 'espace', 12, 10, '/objets/obj-156.svg', 'epic', 'So massive it almost became a star itself.', null),
  ('obj-157', 'Red Giant Star', 'espace', 14, 8, '/objets/obj-157.svg', 'epic', 'Swelling wide enough to swallow its own planets.', null),
  ('obj-158', 'Blue Supergiant Star', 'espace', 17, 7, '/objets/obj-158.svg', 'legendary', 'Among the hottest, brightest stars that exist.', null),
  ('obj-159', 'Supernova', 'espace', 20, 4, '/objets/obj-159.svg', 'legendary', 'A star’s entire life, ending in one blinding instant.', null),
  ('obj-160', 'Pulsar', 'espace', 16, 9, '/objets/obj-160.svg', 'legendary', 'A collapsed star spinning fast enough to sweep light like a lighthouse.', null),
  ('obj-161', 'Quasar', 'espace', 22, 5, '/objets/obj-161.svg', 'secret_rare', 'Brighter than an entire galaxy, powered by a black hole’s appetite.', null),
  ('obj-162', 'Galaxy', 'espace', 21, 11, '/objets/obj-162.svg', 'secret_rare', 'A hundred billion stars, held together by gravity and not much else.', null),
  ('obj-163', 'Sand', 'ressources', 2, 4, '/objets/obj-163.svg', 'common', 'There’s more of it than anything else on the beach.', null),
  ('obj-164', 'Clay', 'ressources', 3, 5, '/objets/obj-164.svg', 'common', 'Wet, moldable, and the start of every brick.', null),
  ('obj-165', 'Limestone', 'ressources', 4, 5, '/objets/obj-165.svg', 'common', 'Built the pyramids and half of every old city since.', null),
  ('obj-166', 'Copper Ore', 'ressources', 5, 6, '/objets/obj-166.svg', 'uncommon', 'One of the first metals humans ever worked.', null),
  ('obj-167', 'Salt Crystal', 'ressources', 4, 5, '/objets/obj-167.svg', 'uncommon', 'Once worth its weight in actual currency.', null),
  ('obj-168', 'Cobalt Ore', 'ressources', 6, 6, '/objets/obj-168.svg', 'uncommon', 'Named for the mine spirits miners blamed for bad luck.', null),
  ('obj-169', 'Silver Ingot', 'ressources', 6, 8, '/objets/obj-169.svg', 'rare', 'Bright, valuable, and tarnishes if you ignore it.', null),
  ('obj-170', 'Quartz Crystal', 'ressources', 7, 7, '/objets/obj-170.svg', 'rare', 'Common enough to find, clear enough to prize.', null),
  ('obj-171', 'Obsidian Shard', 'ressources', 9, 5, '/objets/obj-171.svg', 'rare', 'Volcanic glass, sharper than any forged blade.', null),
  ('obj-172', 'Pearl', 'ressources', 6, 9, '/objets/obj-172.svg', 'rare', 'An accident an oyster turned into a gem.', null),
  ('obj-173', 'Amber', 'ressources', 7, 8, '/objets/obj-173.svg', 'rare', 'Tree resin, patient enough to become a fossil.', null),
  ('obj-174', 'Platinum Ingot', 'ressources', 8, 10, '/objets/obj-174.svg', 'epic', 'Rarer than gold, and it knows it.', null),
  ('obj-175', 'Ruby', 'ressources', 9, 9, '/objets/obj-175.svg', 'epic', 'Corundum with just enough chromium to turn heads.', null),
  ('obj-176', 'Sapphire', 'ressources', 8, 10, '/objets/obj-176.svg', 'epic', 'The same mineral as a ruby, in a very different mood.', null),
  ('obj-177', 'Titanium Ingot', 'ressources', 9, 11, '/objets/obj-177.svg', 'epic', 'Strong as steel, half the weight.', null),
  ('obj-178', 'Emerald', 'ressources', 10, 11, '/objets/obj-178.svg', 'legendary', 'Flawless ones are rarer than diamonds of the same size.', null),
  ('obj-179', 'Uranium Ore', 'ressources', 15, 7, '/objets/obj-179.svg', 'legendary', 'A rock that keeps a Geiger counter very busy.', null),
  ('obj-180', 'Meteorite Fragment', 'ressources', 12, 13, '/objets/obj-180.svg', 'secret_rare', 'Older than the Earth itself, and it fell right onto it.', null),
  ('obj-181', 'Antimatter Sample', 'ressources', 18, 8, '/objets/obj-181.svg', 'secret_rare', 'The rarest substance in the universe. Do not touch the container.', null),
  ('obj-182', 'Dandelion', 'plantes', 2, 4, '/objets/obj-182.svg', 'common', 'A weed to some, a wish to everyone else.', null),
  ('obj-183', 'Clover', 'plantes', 2, 5, '/objets/obj-183.svg', 'common', 'Find one with four leaves and suddenly it’s special.', null),
  ('obj-184', 'Grass Tuft', 'plantes', 2, 4, '/objets/obj-184.svg', 'common', 'Grows back no matter how often it’s cut.', null),
  ('obj-185', 'Poison Ivy', 'plantes', 6, 3, '/objets/obj-185.svg', 'common', 'Three leaves, one very itchy lesson.', null),
  ('obj-186', 'Fern', 'plantes', 3, 6, '/objets/obj-186.svg', 'uncommon', 'Older than flowers, older than dinosaurs.', null),
  ('obj-187', 'Bamboo Stalk', 'plantes', 5, 7, '/objets/obj-187.svg', 'uncommon', 'Grows nearly a meter in a single day.', null),
  ('obj-188', 'Cherry Blossom', 'plantes', 3, 5, '/objets/obj-188.svg', 'uncommon', 'Beautiful for about a week a year, worth the wait.', null),
  ('obj-189', 'Mistletoe', 'plantes', 4, 5, '/objets/obj-189.svg', 'uncommon', 'A parasite that somehow became a holiday tradition.', null),
  ('obj-190', 'Rose', 'plantes', 7, 5, '/objets/obj-190.svg', 'rare', 'Thorns first, petals second.', null),
  ('obj-191', 'Sunflower', 'plantes', 5, 8, '/objets/obj-191.svg', 'rare', 'Turns to follow the sun all day, every day.', null),
  ('obj-192', 'Venus Flytrap', 'plantes', 9, 4, '/objets/obj-192.svg', 'rare', 'A plant that hunts. Snaps shut in under a second.', null),
  ('obj-193', 'Baobab Tree', 'plantes', 6, 12, '/objets/obj-193.svg', 'rare', 'Stores thousands of liters of water in its trunk.', null),
  ('obj-194', 'Orchid', 'plantes', 6, 8, '/objets/obj-194.svg', 'epic', 'One of the largest, oldest flowering plant families alive.', null),
  ('obj-195', 'Giant Sequoia', 'plantes', 8, 15, '/objets/obj-195.svg', 'epic', 'Among the largest living things on the planet.', null),
  ('obj-196', 'Lotus Flower', 'plantes', 7, 10, '/objets/obj-196.svg', 'epic', 'Rises clean out of the mud, every single time.', null),
  ('obj-197', 'Redwood', 'plantes', 8, 14, '/objets/obj-197.svg', 'epic', 'Some have been standing since before recorded history.', null),
  ('obj-198', 'Corpse Flower', 'plantes', 10, 9, '/objets/obj-198.svg', 'legendary', 'Blooms once a decade, and smells like it’s not sorry.', null),
  ('obj-199', 'Ghost Orchid', 'plantes', 9, 11, '/objets/obj-199.svg', 'legendary', 'Leafless, rootless, and almost never seen blooming.', null),
  ('obj-200', 'Jade Vine', 'plantes', 11, 10, '/objets/obj-200.svg', 'secret_rare', 'Glows an unreal turquoise that photos never quite capture.', null),
  ('obj-201', 'Wollemi Pine', 'plantes', 10, 13, '/objets/obj-201.svg', 'secret_rare', 'Thought extinct for two million years, until it wasn’t.', null),
  ('obj-202', 'Tulip', 'plantes', 3, 5, '/objets/obj-202.svg', 'common', 'Once traded for more than gold, back when a single bulb could buy a house.', null),
  ('obj-203', 'Wheat Stalk', 'plantes', 2, 5, '/objets/obj-203.svg', 'common', 'Feeds half the planet, one field at a time.', null),
  ('obj-204', 'Moss', 'plantes', 2, 4, '/objets/obj-204.svg', 'common', 'Grows on anything that holds still long enough.', null),
  ('obj-205', 'Maple Tree', 'plantes', 4, 7, '/objets/obj-205.svg', 'uncommon', 'Bleeds sap sweet enough to bottle.', null),
  ('obj-206', 'Palm Tree', 'plantes', 4, 6, '/objets/obj-206.svg', 'uncommon', 'Bends in the storm instead of breaking.', null),
  ('obj-207', 'Water Lily', 'plantes', 3, 6, '/objets/obj-207.svg', 'uncommon', 'Floats perfectly still on water that never stops moving.', null),
  ('obj-208', 'Pitcher Plant', 'plantes', 8, 4, '/objets/obj-208.svg', 'rare', 'A pool of digestive fluid, dressed up as a flower.', null),
  ('obj-209', 'Bird of Paradise', 'plantes', 6, 6, '/objets/obj-209.svg', 'rare', 'Shaped like the tropical bird it’s named for.', null),
  ('obj-210', 'Passion Flower', 'plantes', 6, 7, '/objets/obj-210.svg', 'rare', 'One of the most intricate blooms nature ever bothered designing.', null),
  ('obj-211', 'Silver Birch', 'plantes', 6, 12, '/objets/obj-211.svg', 'epic', 'Bark so pale it glows under moonlight.', null),
  ('obj-212', 'Dragon Blood Tree', 'plantes', 9, 10, '/objets/obj-212.svg', 'epic', 'Bleeds a deep red resin when its bark is cut.', null),
  ('obj-213', 'Banyan Tree', 'plantes', 7, 13, '/objets/obj-213.svg', 'epic', 'Grows new trunks from its own branches until it becomes a forest.', null),
  ('obj-214', 'Rafflesia', 'plantes', 9, 10, '/objets/obj-214.svg', 'legendary', 'The largest single flower on Earth. Smells exactly as bad as it looks impressive.', null),
  ('obj-215', 'Middlemist Red', 'plantes', 10, 12, '/objets/obj-215.svg', 'secret_rare', 'Only two of these camellias are known to exist on the entire planet.', null),
  ('obj-216', 'Gravel', 'ressources', 3, 4, '/objets/obj-216.svg', 'common', 'Crushed rock, useful for roads and not much glory.', null),
  ('obj-217', 'Gypsum', 'ressources', 3, 5, '/objets/obj-217.svg', 'common', 'Soft enough to scratch with a fingernail, common everywhere.', null),
  ('obj-218', 'Tin Ore', 'ressources', 4, 6, '/objets/obj-218.svg', 'uncommon', 'Mixed with copper, it started the Bronze Age.', null),
  ('obj-219', 'Zinc Ore', 'ressources', 5, 6, '/objets/obj-219.svg', 'uncommon', 'Unglamorous, but nothing galvanized rusts without it.', null),
  ('obj-220', 'Granite Block', 'ressources', 5, 7, '/objets/obj-220.svg', 'uncommon', 'Countertops and cathedrals, cut from the same stone.', null),
  ('obj-221', 'Nickel Ingot', 'ressources', 6, 8, '/objets/obj-221.svg', 'rare', 'Resists corrosion better than metals twice its price.', null),
  ('obj-222', 'Opal', 'ressources', 6, 8, '/objets/obj-222.svg', 'rare', 'Flashes every color at once when it catches the light.', null),
  ('obj-223', 'Garnet', 'ressources', 7, 7, '/objets/obj-223.svg', 'rare', 'January’s birthstone, deep red and deceptively tough.', null),
  ('obj-224', 'Palladium', 'ressources', 8, 9, '/objets/obj-224.svg', 'epic', 'Rarer than platinum, and every catalytic converter wants it.', null),
  ('obj-225', 'Topaz', 'ressources', 8, 9, '/objets/obj-225.svg', 'epic', 'Clear as glass, hard as anything short of a diamond.', null),
  ('obj-226', 'Painite', 'ressources', 10, 10, '/objets/obj-226.svg', 'legendary', 'Once the rarest gem in the Guinness World Records, one crystal at a time.', null),
  ('obj-227', 'Rhodium', 'ressources', 11, 9, '/objets/obj-227.svg', 'legendary', 'The most expensive precious metal, gram for gram.', null),
  ('obj-228', 'Musgravite', 'ressources', 12, 12, '/objets/obj-228.svg', 'secret_rare', 'So rare that gemologists have catalogued barely a handful of stones.', null),
  ('obj-229', 'Cosmic Ray', 'espace', 4, 3, '/objets/obj-229.svg', 'common', 'A particle that’s been traveling since before the Earth existed.', null),
  ('obj-230', 'Solar Wind', 'espace', 4, 4, '/objets/obj-230.svg', 'common', 'A constant stream of particles the Sun never stops throwing off.', null),
  ('obj-231', 'Interstellar Gas Cloud', 'espace', 3, 5, '/objets/obj-231.svg', 'common', 'The raw material waiting to become the next generation of stars.', null),
  ('obj-232', 'Comet Tail', 'espace', 6, 4, '/objets/obj-232.svg', 'uncommon', 'Ice and dust, streaming away from the heat of the sun.', null),
  ('obj-233', 'Binary Star System', 'espace', 8, 6, '/objets/obj-233.svg', 'uncommon', 'Two suns, locked in orbit around each other forever.', null),
  ('obj-234', 'Ring System', 'espace', 6, 8, '/objets/obj-234.svg', 'uncommon', 'Countless chunks of ice and rock, circling in perfect formation.', null),
  ('obj-235', 'Exoplanet', 'espace', 8, 8, '/objets/obj-235.svg', 'rare', 'A world orbiting a star that isn’t ours.', null),
  ('obj-236', 'Brown Dwarf', 'espace', 9, 7, '/objets/obj-236.svg', 'rare', 'Too small to be a star, too big to be a planet.', null),
  ('obj-237', 'Ice Giant', 'espace', 9, 8, '/objets/obj-237.svg', 'rare', 'Cold, blue, and wrapped in a howling atmosphere.', null),
  ('obj-238', 'Neutron Star', 'espace', 11, 6, '/objets/obj-238.svg', 'rare', 'So dense a teaspoon of it would outweigh a mountain.', null),
  ('obj-239', 'Yellow Dwarf Star', 'espace', 12, 8, '/objets/obj-239.svg', 'epic', 'An ordinary star, exactly the kind most solar systems are built around.', null),
  ('obj-240', 'Protostar', 'espace', 11, 9, '/objets/obj-240.svg', 'epic', 'Still collapsing, still gathering mass, not quite a star yet.', null),
  ('obj-241', 'Magnetar', 'espace', 15, 7, '/objets/obj-241.svg', 'epic', 'A magnetic field powerful enough to wipe a hard drive from another planet.', null),
  ('obj-242', 'Hypergiant Star', 'espace', 17, 8, '/objets/obj-242.svg', 'legendary', 'Among the most massive, most luminous stars ever measured.', null),
  ('obj-243', 'Wormhole', 'espace', 16, 9, '/objets/obj-243.svg', 'legendary', 'A theoretical shortcut through spacetime itself.', null),
  ('obj-244', 'The Big Bang', 'espace', 22, 3, '/objets/obj-244.svg', 'secret_rare', 'The event that started literally everything, thirteen billion years ago.', null),
  ('obj-245', 'Observable Universe', 'espace', 20, 12, '/objets/obj-245.svg', 'secret_rare', 'Everything we can possibly ever see, in one card.', null),
  ('obj-246', 'Hedgehog', 'animaux', 4, 6, '/objets/obj-246.svg', 'uncommon', 'Rolls into a spiky ball and calls it a defense plan.', null),
  ('obj-247', 'Otter', 'animaux', 5, 5, '/objets/obj-247.svg', 'uncommon', 'Cracks shellfish open with a favorite rock it keeps for the purpose.', null),
  ('obj-248', 'Honey Badger', 'animaux', 9, 7, '/objets/obj-248.svg', 'rare', 'Famously afraid of nothing, including things that should kill it.', null),
  ('obj-249', 'Vulture', 'animaux', 7, 5, '/objets/obj-249.svg', 'rare', 'Doesn’t hunt. Just waits.', null),
  ('obj-250', 'Hippopotamus', 'animaux', 12, 10, '/objets/obj-250.svg', 'epic', 'Technically a herbivore. Still kills more people than lions do.', null),
  ('obj-251', 'Silverback Gorilla', 'animaux', 13, 11, '/objets/obj-251.svg', 'legendary', 'Strong enough to bend steel bars, calm enough not to bother.', null),
  ('obj-252', 'Canoe', 'vehicules', 3, 5, '/objets/obj-252.svg', 'common', 'One paddle, one direction, one person’s effort.', null),
  ('obj-253', 'Skis', 'vehicules', 4, 3, '/objets/obj-253.svg', 'common', 'Gravity does most of the actual work.', null),
  ('obj-254', 'Trolley Car', 'vehicules', 6, 6, '/objets/obj-254.svg', 'uncommon', 'Runs on rails laid down over a century ago, still on schedule.', null),
  ('obj-255', 'Biplane', 'vehicules', 7, 5, '/objets/obj-255.svg', 'uncommon', 'Two wings because nobody had figured out one was enough yet.', null),
  ('obj-256', 'Cable Car', 'vehicules', 5, 7, '/objets/obj-256.svg', 'uncommon', 'Hangs from a single cable over a very long drop.', null),
  ('obj-257', 'School Bus', 'vehicules', 8, 9, '/objets/obj-257.svg', 'rare', 'Painted a color nobody could ever mistake for anything else.', null),
  ('obj-258', 'Ambulance', 'vehicules', 8, 8, '/objets/obj-258.svg', 'rare', 'The one vehicle every other vehicle gets out of the way for.', null),
  ('obj-259', 'Freight Train', 'vehicules', 10, 9, '/objets/obj-259.svg', 'rare', 'A hundred cars long, and every single one matters to someone.', null),
  ('obj-260', 'Cruise Ship', 'vehicules', 9, 12, '/objets/obj-260.svg', 'epic', 'A floating hotel that happens to also cross oceans.', null),
  ('obj-261', 'High-Speed Ferry', 'vehicules', 11, 8, '/objets/obj-261.svg', 'epic', 'Skims across the water fast enough to nearly fly.', null),
  ('obj-262', 'Semi-Truck', 'vehicules', 12, 10, '/objets/obj-262.svg', 'epic', 'Keeps the country’s shelves stocked, one long haul at a time.', null),
  ('obj-263', 'Supersonic Concorde Jet', 'vehicules', 18, 6, '/objets/obj-263.svg', 'legendary', 'Crossed the Atlantic faster than the sound it made getting there.', null),
  ('obj-264', 'International Space Station', 'vehicules', 14, 15, '/objets/obj-264.svg', 'secret_rare', 'A permanently crewed vehicle, orbiting the planet every ninety minutes.', null)
on conflict (id) do update set
  name = excluded.name,
  category = excluded.category,
  attack = excluded.attack,
  defense = excluded.defense,
  image_url = excluded.image_url,
  rarity = excluded.rarity,
  description = excluded.description,
  explicit_wins = excluded.explicit_wins;
