-- PFC · items catalog seed, GENERATED from pfc/src/mocks by scripts/gen-items-sql.mjs.
-- Re-run the script after the items team changes the catalog; the insert is idempotent.

insert into public.items (id, name, category, attack, defense, image_url, rarity, description, explicit_wins) values
  ('obj-01', 'Mossy Rock', 'ressources', 4, 7, '/objets/obj-01.svg', 'common', 'A good old stone. Solid, if not exactly fast.', null),
  ('obj-04', 'Oak Leaf', 'plantes', 3, 5, '/objets/obj-04.svg', 'common', 'Light and unassuming. Wraps around things without trying.', null),
  ('obj-07', 'Rusty Scissors', 'fight', 5, 3, '/objets/obj-07.svg', 'common', 'Still cuts. Mostly.', null),
  ('obj-02', 'Ancient Menhir', 'ressources', 7, 9, '/objets/obj-02.svg', 'rare', 'Standing for millennia. It doesn''t move, but it blocks everything.', null),
  ('obj-03', 'Meteorite', 'espace', 10, 5, '/objets/obj-03.svg', 'epic', 'Fell from the sky. Hits hard, cracks fast.', null),
  ('obj-05', 'Cursed Scroll', 'plantes', 8, 4, '/objets/obj-05.svg', 'rare', 'Its runes burn anyone who reads them aloud.', null),
  ('obj-06', 'Armored Paper', 'plantes', 5, 8, '/objets/obj-06.svg', 'rare', 'Folded a hundred times. No scissors have gotten through yet.', null),
  ('obj-08', 'Sharpened Katana', 'fight', 11, 4, '/objets/obj-08.svg', 'epic', 'Cuts paper before it even hits the floor.', null),
  ('obj-09', 'Crab Claw', 'fight', 6, 6, '/objets/obj-09.svg', 'rare', 'A natural pincer, balanced and surprisingly tough.', null),
  ('obj-10', 'Storm Lightning', 'fight', 12, 2, '/objets/obj-10.svg', 'legendary', 'Ignores the usual rules. Nobody really knows what it beats.', null),
  ('obj-11', 'Ice Shield', 'fight', 2, 12, '/objets/obj-11.svg', 'epic', 'Freezes whatever it touches. Melts in the first bit of sun.', null),
  ('obj-12', 'Chaos Die', 'fight', 7, 7, '/objets/obj-12.svg', 'legendary', 'Its stats change with every roll. In theory, anyway.', null),
  ('obj-13', 'Hatchet', 'fight', 9, 4, '/objets/obj-13.svg', 'rare', 'Always ends up splitting whatever''s supposed to stop it.', array['obj-14', 'obj-11']::text[]),
  ('obj-14', 'Shield', 'fight', 3, 10, '/objets/obj-14.svg', 'common', 'Deflects hits — except from the hatchet, which gets through eventually.', array['obj-16']::text[]),
  ('obj-15', 'Net', 'plantes', 4, 6, '/objets/obj-15.svg', 'uncommon', 'Wraps and traps, but doesn''t do well near open flame.', null),
  ('obj-16', 'Torch', 'fight', 8, 3, '/objets/obj-16.svg', 'rare', 'Burns anything woven or braided.', array['obj-15', 'obj-18']::text[]),
  ('obj-17', 'Hammer', 'fight', 9, 5, '/objets/obj-17.svg', 'common', 'Flattens anything that can be knocked over.', array['obj-20']::text[]),
  ('obj-18', 'Rope', 'plantes', 3, 5, '/objets/obj-18.svg', 'uncommon', 'Ties down anything drawn to metal.', array['obj-19']::text[]),
  ('obj-19', 'Magnet', 'fight', 6, 6, '/objets/obj-19.svg', 'epic', 'Attracts and locks down anything containing metal.', array['obj-13', 'obj-14', 'obj-17']::text[]),
  ('obj-20', 'Water Bucket', 'fight', 4, 4, '/objets/obj-20.svg', 'uncommon', 'Puts out anything on fire.', array['obj-16']::text[]),
  ('obj-21', 'Kitchen Knife', 'fight', 6, 3, '/objets/obj-21.svg', 'common', 'Cuts clean, but rusts fast if you don''t wipe it down.', null),
  ('obj-22', 'Shovel', 'fight', 5, 7, '/objets/obj-22.svg', 'common', 'Digs, bashes, turns over soil. Simple and unbreakable.', null),
  ('obj-23', 'Umbrella', 'plantes', 3, 6, '/objets/obj-23.svg', 'uncommon', 'Folds shut on the enemy like a closing leaf.', null),
  ('obj-24', 'Fire Extinguisher', 'fight', 5, 5, '/objets/obj-24.svg', 'common', 'Smothers flames in a cold blast of CO2.', null),
  ('obj-25', 'Brick', 'ressources', 6, 6, '/objets/obj-25.svg', 'common', 'Just a paving stone. Unbreakable and unimaginative.', null),
  ('obj-26', 'Duct Tape', 'plantes', 2, 5, '/objets/obj-26.svg', 'uncommon', 'Fixes, sticks, immobilizes. The universal answer.', null),
  ('obj-27', 'Flashlight', 'fight', 4, 4, '/objets/obj-27.svg', 'uncommon', 'A beam that blinds more than it hurts.', null),
  ('obj-28', 'Power Drill', 'fight', 9, 4, '/objets/obj-28.svg', 'rare', 'Pierces almost anything that doesn''t move fast enough.', null),
  ('obj-29', 'Crossbow', 'fight', 10, 3, '/objets/obj-29.svg', 'rare', 'One well-placed bolt goes through light armor.', null),
  ('obj-30', 'Grappling Hook', 'plantes', 5, 8, '/objets/obj-30.svg', 'rare', 'Latches onto anything, drags the fight where it wants.', null),
  ('obj-31', 'Slingshot', 'fight', 7, 5, '/objets/obj-31.svg', 'rare', 'Launches stones with frightening accuracy.', null),
  ('obj-32', 'Boxing Glove', 'fight', 8, 6, '/objets/obj-32.svg', 'rare', 'One hook is enough to knock anyone off balance.', null),
  ('obj-33', 'Circular Saw', 'fight', 10, 4, '/objets/obj-33.svg', 'rare', 'A blade spinning faster than any reflex.', null),
  ('obj-34', 'Chainsaw', 'fight', 13, 5, '/objets/obj-34.svg', 'epic', 'Doesn''t cut, it devours. Loud, vicious, feared.', null),
  ('obj-35', 'Flamethrower', 'fight', 14, 4, '/objets/obj-35.svg', 'epic', 'Turns anything woven, roped, or leafy into ash in a second.', null),
  ('obj-36', 'Heavy Armor', 'fight', 4, 15, '/objets/obj-36.svg', 'epic', 'Takes almost everything. Heavy, slow, nearly indestructible.', null),
  ('obj-37', 'Industrial Drill', 'fight', 15, 6, '/objets/obj-37.svg', 'epic', 'Bores through rock like butter. Nothing holds it back for long.', null),
  ('obj-38', 'Cannon', 'fight', 18, 3, '/objets/obj-38.svg', 'legendary', 'One blast, and there''s not much left standing.', null),
  ('obj-39', 'Tesla Generator', 'fight', 16, 8, '/objets/obj-39.svg', 'legendary', 'A continuous arc that fries any circuit nearby.', null),
  ('obj-40', 'Bottled Tornado', 'fight', 12, 12, '/objets/obj-40.svg', 'legendary', 'Captured wind that breaks loose the moment you open the cap.', null),
  ('obj-41', 'Iron Ore', 'ressources', 5, 6, '/objets/obj-41.svg', 'common', 'Straight from the mine. Rough, heavy, useful.', null),
  ('obj-42', 'Wood Log', 'ressources', 3, 5, '/objets/obj-42.svg', 'common', 'Freshly cut. Burns well, builds better.', null),
  ('obj-43', 'Coal', 'ressources', 4, 4, '/objets/obj-43.svg', 'common', 'Black, dusty, and surprisingly dense.', null),
  ('obj-44', 'Gold Ingot', 'ressources', 6, 8, '/objets/obj-44.svg', 'rare', 'Heavy in the hand, heavier in value.', null),
  ('obj-45', 'Raw Diamond', 'ressources', 9, 10, '/objets/obj-45.svg', 'epic', 'Uncut and unpolished, but already nearly impossible to scratch.', null),
  ('obj-46', 'Ancient Oak', 'plantes', 7, 13, '/objets/obj-46.svg', 'epic', 'Deep roots, decades of growth. It doesn''t budge.', null),
  ('obj-47', 'Thorny Bramble', 'plantes', 7, 3, '/objets/obj-47.svg', 'uncommon', 'Thorns that cut anyone careless enough to grab it.', null),
  ('obj-48', 'Poison Mushroom', 'plantes', 8, 3, '/objets/obj-48.svg', 'rare', 'Beautiful, tempting, and absolutely not for eating.', null),
  ('obj-49', 'Desert Cactus', 'plantes', 5, 7, '/objets/obj-49.svg', 'uncommon', 'Stores water for months. Handle with care.', null),
  ('obj-50', 'Climbing Vine', 'plantes', 4, 6, '/objets/obj-50.svg', 'uncommon', 'Grows through anything given enough time.', null),
  ('obj-51', 'Asteroid', 'espace', 9, 6, '/objets/obj-51.svg', 'rare', 'A wandering rock with nowhere in particular to be.', null),
  ('obj-52', 'Icy Comet', 'espace', 7, 7, '/objets/obj-52.svg', 'rare', 'Streaks by once, leaves a trail of frost.', null),
  ('obj-53', 'Moon', 'espace', 6, 14, '/objets/obj-53.svg', 'epic', 'Pulls the tides without lifting a finger.', null),
  ('obj-54', 'Sun', 'espace', 20, 6, '/objets/obj-54.svg', 'secret_rare', 'The center of everything. Everyone orbits it eventually.', null),
  ('obj-55', 'Shooting Star', 'espace', 10, 4, '/objets/obj-55.svg', 'rare', 'Gone in a second, but everyone makes a wish.', null),
  ('obj-56', 'Miniature Black Hole', 'espace', 22, 2, '/objets/obj-56.svg', 'secret_rare', 'Small enough to hold. Terrifying to get close to.', null),
  ('obj-57', 'Nebula', 'espace', 11, 11, '/objets/obj-57.svg', 'epic', 'A cloud of dust and light, slowly becoming something else.', null),
  ('obj-58', 'Tralalero Tralala', 'brainrot', 17, 9, '/objets/obj-58.svg', 'secret_rare', 'A shark in sneakers. Don''t ask, just accept it.', null),
  ('obj-59', 'Bombardiro Crocodilo', 'brainrot', 19, 7, '/objets/obj-59.svg', 'secret_rare', 'Half crocodile, half bomber plane. All chaos.', null),
  ('obj-60', 'Tung Tung Tung Sahur', 'brainrot', 13, 8, '/objets/obj-60.svg', 'epic', 'Knocks with a rhythm nobody can predict.', null),
  ('obj-61', 'Chimpanzini Bananini', 'brainrot', 9, 8, '/objets/obj-61.svg', 'rare', 'Part monkey, part banana, entirely unbothered.', null),
  ('obj-62', 'Ballerina Cappuccina', 'brainrot', 8, 9, '/objets/obj-62.svg', 'rare', 'Pirouettes with a full cup balanced on her head. Never spills.', null),
  ('obj-63', 'Lirili Larila', 'brainrot', 10, 12, '/objets/obj-63.svg', 'epic', 'An elephant with a cactus for a body. It just works.', null),
  ('obj-64', 'Cappuccino Assassino', 'brainrot', 14, 6, '/objets/obj-64.svg', 'epic', 'Silent, caffeinated, and always one step ahead.', null),
  ('obj-65', 'Boneca Ambalabu', 'brainrot', 6, 6, '/objets/obj-65.svg', 'common', 'Nobody''s quite sure what it is. It''s just vibing.', null)
on conflict (id) do update set
  name = excluded.name,
  category = excluded.category,
  attack = excluded.attack,
  defense = excluded.defense,
  image_url = excluded.image_url,
  rarity = excluded.rarity,
  description = excluded.description,
  explicit_wins = excluded.explicit_wins;
