-- PFC · items catalog seed, GENERATED from pfc/src/mocks by scripts/gen-items-sql.mjs.
-- Re-run the script after the items team changes the catalog; the insert is idempotent.

insert into public.items (id, name, category, attack, defense, image_url, rarity, description, explicit_wins) values
  ('obj-01', 'Mossy Rock', 'ressources', 4, 7, '/objets/obj-01.svg', 'common', null, null),
  ('obj-04', 'Oak Leaf', 'plantes', 3, 5, '/objets/obj-04.svg', 'common', null, null),
  ('obj-07', 'Rusty Scissors', 'fight', 5, 3, '/objets/obj-07.svg', 'common', null, null),
  ('obj-02', 'Ancient Menhir', 'ressources', 7, 9, '/objets/obj-02.svg', 'rare', null, null),
  ('obj-03', 'Meteorite', 'espace', 10, 5, '/objets/obj-03.svg', 'epic', null, null),
  ('obj-05', 'Cursed Scroll', 'plantes', 8, 4, '/objets/obj-05.svg', 'rare', null, null),
  ('obj-06', 'Armored Paper', 'plantes', 5, 8, '/objets/obj-06.svg', 'rare', null, null),
  ('obj-08', 'Sharpened Katana', 'fight', 11, 4, '/objets/obj-08.svg', 'epic', null, null),
  ('obj-09', 'Crab Claw', 'fight', 6, 6, '/objets/obj-09.svg', 'rare', null, null),
  ('obj-10', 'Storm Lightning', 'fight', 12, 2, '/objets/obj-10.svg', 'legendary', null, null),
  ('obj-11', 'Ice Shield', 'fight', 2, 12, '/objets/obj-11.svg', 'epic', null, null),
  ('obj-12', 'Chaos Die', 'fight', 7, 7, '/objets/obj-12.svg', 'legendary', null, null),
  ('obj-13', 'Hatchet', 'fight', 9, 4, '/objets/obj-13.svg', 'rare', null, array['obj-14', 'obj-11']::text[]),
  ('obj-14', 'Shield', 'fight', 3, 10, '/objets/obj-14.svg', 'common', null, array['obj-16']::text[]),
  ('obj-15', 'Net', 'plantes', 4, 6, '/objets/obj-15.svg', 'uncommon', null, null),
  ('obj-16', 'Torch', 'fight', 8, 3, '/objets/obj-16.svg', 'rare', null, array['obj-15', 'obj-18']::text[]),
  ('obj-17', 'Hammer', 'fight', 9, 5, '/objets/obj-17.svg', 'common', null, array['obj-20']::text[]),
  ('obj-18', 'Rope', 'plantes', 3, 5, '/objets/obj-18.svg', 'uncommon', null, array['obj-19']::text[]),
  ('obj-19', 'Magnet', 'fight', 6, 6, '/objets/obj-19.svg', 'epic', null, array['obj-13', 'obj-14', 'obj-17']::text[]),
  ('obj-20', 'Water Bucket', 'fight', 4, 4, '/objets/obj-20.svg', 'uncommon', null, array['obj-16']::text[]),
  ('obj-21', 'Kitchen Knife', 'fight', 6, 3, '/objets/obj-21.svg', 'common', null, null),
  ('obj-22', 'Shovel', 'fight', 5, 7, '/objets/obj-22.svg', 'common', null, null),
  ('obj-23', 'Umbrella', 'plantes', 3, 6, '/objets/obj-23.svg', 'uncommon', null, null),
  ('obj-24', 'Fire Extinguisher', 'fight', 5, 5, '/objets/obj-24.svg', 'common', null, null),
  ('obj-25', 'Brick', 'ressources', 6, 6, '/objets/obj-25.svg', 'common', null, null),
  ('obj-26', 'Duct Tape', 'plantes', 2, 5, '/objets/obj-26.svg', 'uncommon', null, null),
  ('obj-27', 'Flashlight', 'fight', 4, 4, '/objets/obj-27.svg', 'uncommon', null, null),
  ('obj-28', 'Power Drill', 'fight', 9, 4, '/objets/obj-28.svg', 'rare', null, null),
  ('obj-29', 'Crossbow', 'fight', 10, 3, '/objets/obj-29.svg', 'rare', null, null),
  ('obj-30', 'Grappling Hook', 'plantes', 5, 8, '/objets/obj-30.svg', 'rare', null, null),
  ('obj-31', 'Slingshot', 'fight', 7, 5, '/objets/obj-31.svg', 'rare', null, null),
  ('obj-32', 'Boxing Glove', 'fight', 8, 6, '/objets/obj-32.svg', 'rare', null, null),
  ('obj-33', 'Circular Saw', 'fight', 10, 4, '/objets/obj-33.svg', 'rare', null, null),
  ('obj-34', 'Chainsaw', 'fight', 13, 5, '/objets/obj-34.svg', 'epic', null, null),
  ('obj-35', 'Flamethrower', 'fight', 14, 4, '/objets/obj-35.svg', 'epic', null, null),
  ('obj-36', 'Heavy Armor', 'fight', 4, 15, '/objets/obj-36.svg', 'epic', null, null),
  ('obj-37', 'Industrial Drill', 'fight', 15, 6, '/objets/obj-37.svg', 'epic', null, null),
  ('obj-38', 'Cannon', 'fight', 18, 3, '/objets/obj-38.svg', 'legendary', null, null),
  ('obj-39', 'Tesla Generator', 'fight', 16, 8, '/objets/obj-39.svg', 'legendary', null, null),
  ('obj-40', 'Bottled Tornado', 'fight', 12, 12, '/objets/obj-40.svg', 'legendary', null, null),
  ('obj-41', 'Iron Ore', 'ressources', 5, 6, '/objets/obj-41.svg', 'common', null, null),
  ('obj-42', 'Wood Log', 'ressources', 3, 5, '/objets/obj-42.svg', 'common', null, null),
  ('obj-43', 'Coal', 'ressources', 4, 4, '/objets/obj-43.svg', 'common', null, null),
  ('obj-44', 'Gold Ingot', 'ressources', 6, 8, '/objets/obj-44.svg', 'rare', null, null),
  ('obj-45', 'Raw Diamond', 'ressources', 9, 10, '/objets/obj-45.svg', 'epic', null, null),
  ('obj-46', 'Ancient Oak', 'plantes', 7, 13, '/objets/obj-46.svg', 'epic', null, null),
  ('obj-47', 'Thorny Bramble', 'plantes', 7, 3, '/objets/obj-47.svg', 'uncommon', null, null),
  ('obj-48', 'Poison Mushroom', 'plantes', 8, 3, '/objets/obj-48.svg', 'rare', null, null),
  ('obj-49', 'Desert Cactus', 'plantes', 5, 7, '/objets/obj-49.svg', 'uncommon', null, null),
  ('obj-50', 'Climbing Vine', 'plantes', 4, 6, '/objets/obj-50.svg', 'uncommon', null, null),
  ('obj-51', 'Asteroid', 'espace', 9, 6, '/objets/obj-51.svg', 'rare', null, null),
  ('obj-52', 'Icy Comet', 'espace', 7, 7, '/objets/obj-52.svg', 'rare', null, null),
  ('obj-53', 'Moon', 'espace', 6, 14, '/objets/obj-53.svg', 'epic', null, null),
  ('obj-54', 'Sun', 'espace', 20, 6, '/objets/obj-54.svg', 'secret_rare', null, null),
  ('obj-55', 'Shooting Star', 'espace', 10, 4, '/objets/obj-55.svg', 'rare', null, null),
  ('obj-56', 'Miniature Black Hole', 'espace', 22, 2, '/objets/obj-56.svg', 'secret_rare', null, null),
  ('obj-57', 'Nebula', 'espace', 11, 11, '/objets/obj-57.svg', 'epic', null, null),
  ('obj-58', 'Tralalero Tralala', 'brainrot', 17, 9, '/objets/obj-58.svg', 'secret_rare', null, null),
  ('obj-59', 'Bombardiro Crocodilo', 'brainrot', 19, 7, '/objets/obj-59.svg', 'secret_rare', null, null),
  ('obj-60', 'Tung Tung Tung Sahur', 'brainrot', 13, 8, '/objets/obj-60.svg', 'epic', null, null),
  ('obj-61', 'Chimpanzini Bananini', 'brainrot', 9, 8, '/objets/obj-61.svg', 'rare', null, null),
  ('obj-62', 'Ballerina Cappuccina', 'brainrot', 8, 9, '/objets/obj-62.svg', 'rare', null, null),
  ('obj-63', 'Lirili Larila', 'brainrot', 10, 12, '/objets/obj-63.svg', 'epic', null, null),
  ('obj-64', 'Cappuccino Assassino', 'brainrot', 14, 6, '/objets/obj-64.svg', 'epic', null, null),
  ('obj-65', 'Boneca Ambalabu', 'brainrot', 6, 6, '/objets/obj-65.svg', 'common', null, null)
on conflict (id) do update set
  name = excluded.name,
  category = excluded.category,
  attack = excluded.attack,
  defense = excluded.defense,
  image_url = excluded.image_url,
  rarity = excluded.rarity,
  description = excluded.description,
  explicit_wins = excluded.explicit_wins;
